# Generated by Django 3.0.5 on 2021-04-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
