# Generated by Django 3.0.5 on 2021-04-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20210427_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название жанра'),
        ),
    ]
