# Generated by Django 3.0.5 on 2021-04-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
        ('reviews', '0003_auto_20210425_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='title',
            name='genre_id',
        ),
        migrations.AlterField(
            model_name='review',
            name='title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='titles.Title'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
